import re

from conversation.menu import _icon, get_menu_options


VISIT_HISTORY_INPUTS = {
    "visit history",
    "appointment history",
    "visit status",
    "appointment status",
    "my appointments",
}

# Regex to strip common emoji characters so button taps with emojis still match.
_EMOJI_PATTERN = re.compile(
    "["
    "\U0001F600-\U0001F64F"  # emoticons
    "\U0001F300-\U0001F5FF"  # symbols & pictographs
    "\U0001F680-\U0001F6FF"  # transport & map
    "\U0001F1E0-\U0001F1FF"  # flags
    "\U00002702-\U000027B0"  # dingbats
    "\U000024C2-\U0001F251"  # misc
    "\U0001F900-\U0001F9FF"  # supplemental symbols
    "\U0001FA00-\U0001FA6F"  # chess symbols
    "\U0001FA70-\U0001FAFF"  # symbols extended-A
    "\U00002600-\U000026FF"  # misc symbols
    "\U0000FE00-\U0000FE0F"  # variation selectors
    "\U0000200D"             # zero-width joiner
    "]+",
    flags=re.UNICODE,
)


def _strip_emoji(text: str) -> str:
    """Remove emoji characters from *text* so plain-label matching still works.

    Whitespace is also normalised (emoji removal can leave double spaces, e.g.
    "🔍 Track my order" -> " Track my order") so that button-tap text matches
    single-space menu candidates.
    """
    cleaned = _EMOJI_PATTERN.sub("", text)
    return re.sub(r"\s+", " ", cleaned).strip()


_NAVIGATION_OPTIONS = (
    {"label": "Human support", "intent": "handover"},
    {"label": "Chat with agent", "intent": "handover"},
    {"label": "Chat with a human agent", "intent": "handover"},
    {"label": "Talk to an agent", "intent": "handover"},
    {"label": "Go back to main menu", "intent": "main_menu"},
    {"label": "Main menu", "intent": "main_menu"},
)

# Keep choices from messages sent before the shorter WhatsApp-safe labels
# were introduced. Customers can still tap an older message without losing
# their place in the conversation.
_LEGACY_LABEL_ALIASES = (
    {"label": "Book a store visit", "intent": "book_visit"},
    {"label": "Report an issue / Alteration", "intent": "alteration_pickup_recent"},
    {"label": "Estimate fabric & price", "intent": "fabric_estimate"},
    {"label": "View price catalog", "intent": "pricing"},
    {"label": "Update my address", "intent": "address_update"},
    {"label": "Track my current order", "intent": "order_status"},
    {"label": "Modify my order", "intent": "order_changes"},
    {"label": "Place a new order / Pickup", "intent": "new_order"},
    {"label": "Place an order / Pickup", "intent": "new_order"},
    {"label": "Drop off fabric at store", "intent": "fabric_delivery"},
    {"label": "Learn about tailorsin.com", "intent": "about"},
    {"label": "Register to place an order / book a visit", "intent": "register"},
)


def _all_menu_options(menu: list[dict[str, str]]) -> list[dict[str, str]]:
    """Return current and cross-segment options, without duplicate intents."""
    options = [*menu, *_NAVIGATION_OPTIONS, *_LEGACY_LABEL_ALIASES]
    for segment in ("active_client", "client", "new_user"):
        options.extend(get_menu_options(segment))

    unique: list[dict[str, str]] = []
    seen: set[tuple[str, str]] = set()
    for item in options:
        key = (item["intent"], item["label"])
        if key not in seen:
            unique.append(item)
            seen.add(key)
    return unique


def _label_variants(label: str, intent: str) -> set[str]:
    """Labels accepted from Telegram and WATI interactive controls."""
    plain = _strip_emoji(label)
    rendered_label = f"{_icon(intent)} {label}"
    return {
        label.casefold(),
        # WATI applies its 20/24-character limits before the provider sends
        # the selection back.  Keep these variants *with* the original emoji
        # as well: stripping an emoji first shifts the truncation boundary
        # (for example, "ℹ️ Learn about tailo").
        label[:24].rstrip().casefold(),
        label[:20].rstrip().casefold(),
        plain.casefold(),
        # Also accept limits applied after emoji removal, which is how WATI
        # list-row labels are generated by this application.
        plain[:24].rstrip().casefold(),
        plain[:20].rstrip().casefold(),
        # build_menu_reply_markup adds an icon before each menu label. WATI
        # limits that rendered title to 20 characters, then returns it as the
        # user's selection, so accept its exact provider-facing variant.
        rendered_label[:24].rstrip().casefold(),
        rendered_label[:20].rstrip().casefold(),
    }


def _find_intent(options: list[dict[str, str]], value: str) -> str | None:
    raw_candidate = value.strip().casefold()
    candidate = _strip_emoji(value).strip().casefold()
    for item in options:
        variants = _label_variants(item["label"], item["intent"])
        if (
            candidate == item["intent"].casefold()
            or candidate in variants
            or raw_candidate in variants
        ):
            return item["intent"]
    return None


def get_intent(client_type, option):

    menu = get_menu_options(client_type)

    normalized_option = option.strip()
    if normalized_option.casefold() in VISIT_HISTORY_INPUTS:
        return "visit_history"

    all_options = _all_menu_options(menu)

    # Support menu_ prefixed callback data (e.g. "menu_order_status")
    if normalized_option.startswith("menu_"):
        intent_key = normalized_option[len("menu_"):]
        for item in all_options:
            if item["intent"] == intent_key:
                return intent_key
        return None

    # Support numeric menu selection (1-based index), optionally prefixed like "1. text"
    plain_option = _strip_emoji(normalized_option)
    if "." in plain_option:
        parts = plain_option.split(".", 1)
        if parts[0].strip().isdigit():
            plain_option = parts[1].strip()

    if plain_option.isdigit():
        index = int(plain_option)
        if index == 0:
            return "main_menu"
        if 1 <= index <= len(menu):
            return menu[index - 1]["intent"]

    match_option = plain_option.strip()

    # WATI may quote the earlier bot message and append the selected label on
    # the final line. Test the whole value first, then each line in reverse.
    candidates = [normalized_option, match_option]
    candidates.extend(reversed([line.strip() for line in normalized_option.splitlines() if line.strip()]))
    for candidate in candidates:
        resolved = _find_intent(all_options, candidate)
        if resolved:
            return resolved

    # Check for common navigation text inputs (exact matches only)
    if normalized_option.casefold() in {"main menu", "main_menu", "menu", "home", "back", "go back"}:
        return "main_menu"

    # Don't match "handover" as common text - only exact match or button tap
    if normalized_option.casefold() == "handover":
        return "handover"

    return None
